import type { Metadata } from 'next'

import { Plus_Jakarta_Sans } from 'next/font/google'

import './normalize.css'
import './globals.css'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body style={{ ...plusJakartaSans.style }}>{children}</body>
    </html>
  )
}
